/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  AnimationPreset,
  QRCodeAnimation,
} from './components/bp-qr-code/animations';


export namespace Components {

  interface BpQrCode {
    'animateQRCode': (animation?: AnimationPreset | QRCodeAnimation) => void;
    'contents': string;
    'getModuleCount': () => number;
    'legacy': boolean;
    'maskXToYRatio': number;
    'moduleColor': string;
    'positionCenterColor': string;
    'positionRingColor': string;
    'protocol': string;
  }
  interface BpQrCodeAttributes extends StencilHTMLAttributes {
    'contents'?: string;
    'legacy'?: boolean;
    'maskXToYRatio'?: number;
    'moduleColor'?: string;
    'onCodeRendered'?: (event: CustomEvent) => void;
    'positionCenterColor'?: string;
    'positionRingColor'?: string;
    'protocol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BpQrCode': Components.BpQrCode;
  }

  interface StencilIntrinsicElements {
    'bp-qr-code': Components.BpQrCodeAttributes;
  }


  interface HTMLBpQrCodeElement extends Components.BpQrCode, HTMLStencilElement {}
  var HTMLBpQrCodeElement: {
    prototype: HTMLBpQrCodeElement;
    new (): HTMLBpQrCodeElement;
  };

  interface HTMLElementTagNameMap {
    'bp-qr-code': HTMLBpQrCodeElement
  }

  interface ElementTagNameMap {
    'bp-qr-code': HTMLBpQrCodeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
